import { describe, it, expect } from "vitest";
import { makeCtx } from "./helpers.js";
import { piiInGeneratedOutput } from "../src/integrity/pii-in-generated-output.js";

/**
 * Personal data embedded in generated output.
 *
 * `pii-in-repo` looks at the HEADER of data files. Once data is embedded in a
 * dashboard or a report there is no header, only addresses scattered through the
 * text — and the rule could not see it. Real case: a harvester's generated HTML
 * page was tracked in git with people's names and addresses embedded in it; the
 * next run would have taken it to 1,847 records.
 */

const ADRESLER = [
  "73 Church Street", "702 Forbes Avenue", "159 Campbell Rd",
  "103 Slawson Dr", "225 Russell Ave", "3643 Warners Rd",
  "208 Skyview Dr", "7900 Owasco Ave",
];

const run = (files: Record<string, string>, overrides?: Parameters<typeof makeCtx>[1]) =>
  piiInGeneratedOutput.run(makeCtx(files, overrides)) as Array<{
    severity: string; description: string; confidence?: string;
  }>;

describe("a02 — personal data in generated output", () => {
  it("BAD: generated HTML, three addresses are enough", () => {
    // In a generated file what matters is not today's count but TOMORROW's: every
    // run embeds more records and every run gets committed.
    const f = run({
      "ui/panel.html": ADRESLER.slice(0, 3).map((a) => `<span>${a} Syracuse NY</span>`).join(""),
      "ui/assemble.py": `open("ui/panel.html", "w").write(html)`,
    });
    expect(f.length).toBe(1);
    expect(f[0].confidence).toBe("certain");
    expect(f[0].description).toContain("ui/assemble.py");
    expect(f[0].description).toContain("GENERATED by");
  });

  it("CLEAN: three addresses do not cross the threshold in a non-generated file", () => {
    // Documentation may carry an example address or two; if the rule catches those,
    // every README becomes a finding and nobody reads it.
    const f = run({
      "docs/ornek.md": ADRESLER.slice(0, 3).map((a) => `- ${a}`).join("\n"),
    });
    expect(f.length).toBe(0);
  });

  it("BAD: eight addresses in a non-generated file is a dataset", () => {
    const f = run({
      "data/BULGULAR.md": ADRESLER.map((a) => `- ${a}`).join("\n"),
    });
    expect(f.length).toBe(1);
    expect(f[0].description).not.toContain("GENERATED by");
  });

  it("CLEAN: gitignored output produces no finding", () => {
    const f = run(
      {
        "ui/panel.html": ADRESLER.map((a) => `<span>${a}</span>`).join(""),
        "ui/assemble.py": `open("ui/panel.html", "w").write(html)`,
      },
      { tracked: ["ui/assemble.py"] },
    );
    expect(f.length).toBe(0);
  });

  it("CLEAN: silent when this is not a git repository", () => {
    const f = run(
      { "ui/panel.html": ADRESLER.map((a) => `<span>${a}</span>`).join("") },
      { isGitRepo: false },
    );
    expect(f.length).toBe(0);
  });

  it("detecting the generator requires a WRITE call, the name appearing is not enough", () => {
    // The first version said "the file name appears in this script AND there is a
    // write somewhere in it"; even a script that only READ the file counted as the
    // generator. When a finding's reason is wrong, trust is lost even if the finding is right.
    const f = run({
      "docs/rapor.md": ADRESLER.map((a) => `- ${a}`).join("\n"),
      "tools/oku.py": `veri = open("docs/rapor.md").read()\nwith open("baska.txt", "w") as f: f.write(veri)`,
    });
    expect(f.length).toBe(1);
    expect(f[0].description).not.toContain("GENERATED by");
  });
});
