import type { Finding } from "../core/finding.js";
import { fileEvidence } from "../core/finding.js";
import type { StaticRule } from "../core/rule.js";

/**
 * A08 — a generated file was edited by hand.
 *
 * It is silently deleted on the next regeneration. Worse: the test that covers
 * the deleted thing can become meaningless at the same moment, so the suite
 * stays green and the loss goes unnoticed.
 */
const URETILDI =
  /(ÜRETİLMİŞ DOSYA|elle düzenlemeyin|do not edit|DO NOT EDIT|auto-?generated|@generated|generated by)/i;

export const generatedFileHandEdited: StaticRule = {
  id: "int-generated-file-hand-edited",
  title: "A generated file was hand-edited; the edit dies on the next regeneration",
  owasp: "A08:2021-Software & Data Integrity Failures",
  severity: "high",
  kind: "static",
  // No preconditions: relies on reading files.
  requires: [],
  confidence: "likely",
  // This rule reads the file's HEADER COMMENT ("GENERATED FILE — do not edit");
  // if comments are blanked out it goes blind.
  scansComments: true,
  run(ctx): Finding[] {
    const findings: Finding[] = [];
    for (const file of ctx.files) {
      if (/node_modules|\.lock$|lock\.json$/.test(file)) continue;
      const content = ctx.read(file);
      if (!content) continue;
      const bas = content.slice(0, 800);
      if (!URETILDI.test(bas)) continue;
      // Find EVERY source that WRITES this file — not just the first.
      //
      // The first version looked at the first match, and that was usually the
      // script that APPLIES the file (e.g. apply-schema) rather than the one that
      // generates it. A finding was produced even though the real generator had an
      const writers = ctx.grep(new RegExp(file.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")))
        .map((m) => m.file)
        .filter((f, i, hepsi) => hepsi.indexOf(f) === i)
        .filter((f) => /write(File)?(Sync)?\s*\(|fs\.write/i.test(ctx.read(f) || ""));
      if (!writers.length) continue;

      // If ANY of the writers includes an external "additions" file, the pattern is
      // safe: the hand-written part is preserved.
      if (writers.some((f) => /additions|ekler|extra|append|manual|elle/i.test(ctx.read(f) || ""))) continue;
      const uretici = [{ file: writers[0] }];

      findings.push({
        ruleId: "int-generated-file-hand-edited",
        title: "A generated file was hand-edited; the edit dies on the next regeneration",
        owasp: "A08:2021-Software & Data Integrity Failures",
        severity: "high",
        confidence: "likely",
        description:
          `\`${file}\` declares itself generated and is written by \`${uretici[0].file}\`. ` +
          "Anything added by hand disappears silently on the next run.",
        evidence: [fileEvidence(file, 1, bas.split("\n")[0]?.trim() || file)],
        remediation:
          "Move the hand-written part into a SEPARATE file and have the generator append it. " +
          "Then write a test asserting the additions survive regeneration.",
      });
    }
    return findings;
  },
};
