import type { Finding } from "../core/finding.js";
import { fileEvidence } from "../core/finding.js";
import type { StaticContext, StaticRule } from "../core/rule.js";

/**
 * A02 — personal data inside GENERATED output, and the output is in git.
 *
 * `pii-in-repo` looks at the HEADER of data files: CSV, TSV, JSONL. But once
 * the data is EMBEDDED in a report, a dashboard or an HTML page there is no
 * header row — only addresses and names scattered through the text. The rule
 * could not see it.
 *
 * Real case: a harvester's generated HTML page was tracked in git with the
 * names and addresses of 79 people embedded in it. The next run would have made
 * that 1,847. It was found by hand; the tool missed it.
 *
 * Two properties make this kind of file dangerous: it is GENERATED (so every
 * run embeds more data) and it is TRACKED (so every run gets committed).
 */

/** Sokak adresi desenleri. */
const ADRES_DESENLERI = [
  // ABD: 123 Main St / 45 Forbes Avenue
  /\b\d{1,6}\s+[A-Z][A-Za-z]{2,}\s+(St|Street|Ave|Avenue|Rd|Road|Dr|Drive|Ln|Lane|Blvd|Boulevard|Ct|Court|Way|Pl|Place|Ter|Terrace|Cir|Circle|Hwy|Pkwy)\b/g,
  // Turkish addresses: Atatürk Mah. / Gül Sok. No:12
  /\b[A-ZÇĞİÖŞÜ][\wçğıöşü]{2,}\s+(Mah\.?|Mahallesi|Sok\.?|Sokak|Cad\.?|Caddesi)\b/g,
];

const OUTPUT_FILE = /\.(html?|md|txt|rst|csv\.html)$/i;

/** Is this file produced by a script? */
function uretiliyorMu(ctx: StaticContext, file: string): string | null {
  // The file name has to appear INSIDE THE WRITE CALL.
  //
  // The first version said "the file name appears in this script AND there is a
  // write somewhere in it". The second looked at the neighbouring line — also
  // not enough: a write call next to the line that READS the file made it look
  // like the producer.
  //
  // Even when the finding itself is right, a wrong REASON makes the reader stop
  // trusting it. So the link must be explicit: `open("x", "w")`,
  // `writeFileSync("x", ...)`, `> x`.
  const kacis = file.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const YAZMA_ICINDE = new RegExp(
    [
      `open\\s*\\(\\s*["'\`][^"'\`]*${kacis}[^"'\`]*["'\`]\\s*,\\s*["'\`][wa]`,
      `write(File)?(Sync)?\\s*\\(\\s*[^,)]*${kacis}`,
      `>\\s*["']?[^"'\\s]*${kacis}`,
    ].join("|"),
  );

  for (const m of ctx.grep(new RegExp(kacis))) {
    if (m.file === file) continue;
    if (YAZMA_ICINDE.test(m.text)) return m.file;
  }
  return null;
}

/**
 * The threshold.
 *
 * Documentation may carry an example address or two; if the rule catches those,
 * every README becomes a finding and nobody reads it. Eight DIFFERENT addresses
 * are not an example, they are a dataset.
 */
const ESIK = 8;

/**
 * The threshold is lower for a GENERATED file.
 *
 * In the real case the file held only six DIFFERENT addresses — below the
 * threshold of eight — but it was produced by a script and every run would embed
 * more records (79 → 1,847). A generated output has no business being in git at
 * all; when it contains personal data, what matters is not today's count but tomorrow's.
 */
const URETILEN_ESIK = 3;

export const piiInGeneratedOutput: StaticRule = {
  id: "a02-pii-in-generated-output",
  title: "Generated output embeds personal data and is committed to git",
  owasp: "A02:2021-Cryptographic Failures",
  severity: "high",
  kind: "static",
  // No preconditions: relies on reading files.
  requires: [],
  confidence: "certain",
  cwe: "CWE-359",
  // This rule looks at the file's TEXT; comments and prose carry data too.
  scansComments: true,
  run(ctx): Finding[] {
    if (!ctx.isGitRepo) return [];

    const findings: Finding[] = [];
    for (const file of ctx.files) {
      if (!OUTPUT_FILE.test(file)) continue;
      if (!ctx.isTracked(file)) continue;

      const content = ctx.readHead(file, 512 * 1024);
      if (!content) continue;

      const adresler = new Set<string>();
      for (const desen of ADRES_DESENLERI) {
        for (const m of content.matchAll(desen)) adresler.add(m[0].trim());
      }
      if (!adresler.size) continue;

      const uretici = uretiliyorMu(ctx, file);
      if (adresler.size < (uretici ? URETILEN_ESIK : ESIK)) continue;
      findings.push({
        ruleId: "a02-pii-in-generated-output",
        title: "Generated output embeds personal data and is committed to git",
        owasp: "A02:2021-Cryptographic Failures",
        severity: "high",
        confidence: "certain",
        cwe: "CWE-359",
        description:
          `\`${file}\` is tracked by git and embeds at least ${adresler.size} distinct street address(es) ` +
          `(e.g. ${[...adresler].slice(0, 2).join(", ")}). ` +
          (uretici
            ? `The file is GENERATED by \`${uretici}\`, so every run embeds more data and every run gets committed.`
            : "It is not a data file, yet it carries data; with no header row, the table rules never see it."),
        evidence: [fileEvidence(file, 1, [...adresler].slice(0, 3).join(" · "))],
        remediation:
          "Add the generated output to `.gitignore` and untrack it with `git rm --cached`; a generated " +
          "file has no business living in source anyway. If it must be published, put it somewhere with " +
          "restricted access. If the repository has not been pushed, purge the history too — ⚠ `--invert-paths` " +
          "deletes EVERYTHING on the list, so never list a file you want to keep; take a `git bundle` backup first.",
      });
    }
    return findings;
  },
};
